sudo: false
language: python
python:
  - "3.7"

services:
  - xvfb

before_install:
  - sudo apt-get install graphviz

install:
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable bikeshed

script:
  - cd .build
  - ./gradlew generateBikeshed
  - chmod +x ../bikeshed-gen/publish.sh
  - ../bikeshed-gen/publish.sh

env:
  global:
  - ENCRYPTION_LABEL: "26c87bd483ba"
  - COMMIT_AUTHOR_EMAIL: "melaasar@gmail.com"

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    dry-run: false
    on:
      branch: master