bikeshed spec opencaesar.io/foundation/analysis.bs
bikeshed spec opencaesar.io/foundation/base.bs
bikeshed spec opencaesar.io/foundation/mission.bs
bikeshed spec opencaesar.io/foundation/project.bs
bikeshed spec purl.org/dc/elements/1.1.bs
bikeshed spec www.w3.org/1999/02/22-rdf-syntax-ns.bs
bikeshed spec www.w3.org/2000/01/rdf-schema.bs
bikeshed spec www.w3.org/2001/XMLSchema.bs
bikeshed spec www.w3.org/2002/07/owl.bs
